// The Atom feed.
//
// Generated by the pipeline onto the `data` branch, not at build time. A feed
// that only refreshed when the *code* changed would be stale by days, which
// defeats the point — and rebuilding the site on every data refresh is exactly
// the coupling ADR 0003 exists to avoid.
//
// Atom rather than RSS 2.0: dates are unambiguous (RFC 3339, no locale-
// dependent parsing) and entry identity is a first-class field, which matters
// because the same feature can appear repeatedly as it slips again.

/**
 * What is worth interrupting someone for.
 *
 * Deliberately excludes `added`, `shipped`, `date_added` and `preview_set`:
 * a single run produced 13 `added` events, and a feed that fires on routine
 * announcements is a feed people unsubscribe from. What is left is the news
 * nobody else reports — things getting later, smaller, or disappearing.
 */
import { featureId, sourceLink } from './links.mjs';

export const NOTABLE_TYPES = new Set([
  'slipped',
  'cancelled',
  'dropped',
  'scope_reduced',
  'retirement_moved',
  'retirement_announced',
]);

/** How many entries the feed carries. */
export const FEED_LIMIT = 50;

/** Escape the five characters XML cannot carry raw. Order matters: & first. */
export function escapeXml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const signed = (n) => (n > 0 ? `+${n}` : String(n));

/** "+1 month", "+3 months" — the singular matters in a title people read. */
const amount = (n, unit) => `${signed(n)} ${Math.abs(n) === 1 ? unit : `${unit}s`}`;

/**
 * A headline that carries the news without needing the body.
 *
 * Most feed readers show titles in a list, so "Slipped +7 months — …" has to
 * be self-contained. A bare feature name would make every entry look alike.
 */
export function entryTitle(event) {
  const name = event.title ?? '';
  switch (event.type) {
    case 'slipped':
      return `Slipped ${amount(event.months ?? 0, 'month')} — ${name}`;
    case 'cancelled':
      return `Cancelled — ${name}`;
    case 'dropped':
      return `Dropped from the roadmap — ${name}`;
    case 'scope_reduced':
      return `Scope cut (${event.fromRaw ?? 'reduced'}) — ${name}`;
    case 'retirement_moved':
      return `Retirement moved ${amount(event.days ?? 0, 'day')} — ${name}`;
    case 'retirement_announced':
      return `Retirement announced — ${name}`;
    default:
      return name;
  }
}

/** A plain-text body: the move, the product, the source, the feed's own id. */
export function entrySummary(event) {
  const parts = [];
  if (event.from || event.to) parts.push(`${event.from ?? '—'} → ${event.to ?? '—'}`);
  if (event.products?.length) parts.push(event.products.join(', '));
  parts.push(event.source === 'azure' ? 'Azure' : 'Microsoft 365');
  // The roadmap id is how someone looks this up on Microsoft's own site.
  parts.push(`ID ${featureId(event.id)}`);
  return parts.join(' · ');
}

/**
 * Pick and order what goes in the feed.
 *
 * @param {any[]} events
 * @param {number} [limit]
 */
export function feedEntries(events, limit = FEED_LIMIT) {
  return (events ?? [])
    .filter((e) => e && NOTABLE_TYPES.has(e.type))
    .sort((a, b) => String(b.ts).localeCompare(String(a.ts)))
    .slice(0, limit);
}

/**
 * A stable, unique id per entry.
 *
 * A feature that slips twice produces two entries that must not collide, so
 * the id carries the timestamp as well as the item and the kind of change.
 * Readers use this to decide what is already seen — getting it wrong either
 * re-notifies endlessly or silently drops news.
 */
export function entryId(event, siteUrl) {
  return `${siteUrl}#/item/${encodeURIComponent(event.id)}?t=${event.type}&at=${event.ts}`;
}

/**
 * Build the Atom document.
 *
 * @param {{events: any[], generated: string, siteUrl: string, feedUrl: string, limit?: number}} options
 * @returns {string}
 */
export function buildFeed({ events, generated, siteUrl, feedUrl, limit = FEED_LIMIT }) {
  const entries = feedEntries(events, limit);
  // An empty feed still needs a valid `updated`, and the run timestamp is the
  // honest answer: we looked, and there was nothing.
  const updated = entries[0]?.ts ?? generated;

  const body = entries
    .map((event) => {
      const link = `${siteUrl}#/item/${encodeURIComponent(event.id)}`;
      return [
        '  <entry>',
        `    <title>${escapeXml(entryTitle(event))}</title>`,
        `    <id>${escapeXml(entryId(event, siteUrl))}</id>`,
        `    <link rel="alternate" href="${escapeXml(link)}"/>`,
        `    <updated>${escapeXml(event.ts)}</updated>`,
        `    <summary>${escapeXml(entrySummary(event))}</summary>`,
        // Derived, not taken from the stored event: a link recorded under an
        // older, wrong rule would otherwise stay wrong forever.
        `    <link rel="related" href="${escapeXml(sourceLink(event.id, event.source))}"/>`,
        '  </entry>',
      ].filter(Boolean).join('\n');
    })
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Ship or Slip</title>
  <subtitle>Every date Microsoft promised, and every date it moved.</subtitle>
  <id>${escapeXml(siteUrl)}</id>
  <link rel="alternate" href="${escapeXml(siteUrl)}"/>
  <link rel="self" href="${escapeXml(feedUrl)}"/>
  <updated>${escapeXml(updated)}</updated>
${body}
</feed>
`;
}
